name: AMPMatrixRecovery
channels:
  - conda-forge
  - defaults
dependencies:
  - blas[build=mkl]
  - numpy
  - python=3.10
  - pandas
  - autograd
  - scipy
  - google-auth
  - cvxpy
  - jax
  - dask
  - dask-jobqueue
  - coiled
  - sqlalchemy
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git
variables:
  MKL_NUM_THREADS: '1'
  OPENBLAS_NUM_THREADS: '1'
